### ISSUE TITLE
RSC Code Draft

### ISSUE THREAD

**Issue by vrurg** [Raku/Raku-Steering-Council#2]
I open this issue for general matters related to the Code.

**Comment by lizmat** [comment]
I think this issue can be closed now?

**Comment by vrurg** [comment]
Do we consider the paper finalized? I planned to submit a few PRs today, but it seems to be too late.

**Comment by lizmat** [comment]
Let's see the PR's.  I think that ultimately the people mentioned in the announcement can decide on accepting / rejecting them.  At least until the actual voting starts?

**Comment by codesections** [comment]
Closing since the RSC has been elected.
