### ISSUE TITLE
Passive / Active voting for long time contributors without commit bits

### ISSUE THREAD

**Issue by lizmat** [Raku/Raku-Steering-Council#20]
Now that we have postponed the nominations and the election, we should maybe also look at the situation for long time contributors from e.g. the Pugs era, that would like to participate.  Case in point:

    https://twitter.com/wim_v12e/status/1289121069773848576

Wim has recently written some excellent Raku blogs posts, so is definitely involved in the community, I'd say.  Yet he doesn't have any commit bits, so would be left out according to our current definition.

Perhaps we should expand our definition **for this election** to include people who have:

a. a commit bit in roast
b. have written a Raku blog post (note: Raku, not Perl 6, so implies recent)
c. have updated a module to the ecosystem to reflect the name change

Whether this definition would be applicable for future elections, would be up to change for the sitting RSC.  Please note that inclusion in this vote *and* voting, would constitute "activity" and therefore voting rights for the next election.

**Comment by JJ** [comment]
That's going to be incredibly difficult to manage, @lizmat. Look up in three different places to check right to vote. It's difficult enough as it is: there are different teams in the different organizations (raku-community-modules, Raku, perl6, rakudo, MoarVM), but at least that can be partly automatized using the GitHub API.
Let's just give the commit bit somewhere for anyone who we think should have the right to vote. I can do it in the documentation repo, which needs help anyway.

**Comment by lizmat** [comment]
Ah!  Good point, a commit bit in the documentation should also give voting rights for this election.  Perhaps that *is* the easiest manageable way.

**Comment by wimvanderbauwhede** [comment]
Thanks, accepted!

**Comment by coke** [comment]
Followup question as the vote-tallier: Is the expectation that I will match the from field on the email votes to a github ID? I can go from id to email, can I go from email to id?

**Comment by coke** [comment]
Nevermind, this works: https://github.com/search?q=jjmerelo@gmail.com&type=Users - I can do that and then match it against a list.

**Comment by coke** [comment]
I have one person who tried to vote early (already responded to them that the vote won't count because it's early) but also I can't find them in github email search... so I'd have to reject that vote anyway, yes? I'll add a note to the ballot about how we're determining ballot access.

**Comment by coke** [comment]
693bcd16c5d8bc38c73016cf16c2e342fdca27df

**Comment by coke** [comment]
> Maybe just ask for their github id right in the form?

My concern was verification.

**Comment by AlexDaniel** [comment]
> My concern was verification.

Oh. Well, then I don't know what to suggest. Some people don't choose an email address for their profile on github (Settings/Profile/Public email), so you can't really verify an email against a github id.

One ugly way of doing this is to ask people to email a link to a secret gist with their votes… but IIRC you can force-push new contents of gists because they are just git repos. So, I don't know.

**Comment by coke** [comment]
Eh. changed it to ask for github ID, and I'll try to keep an eye on issues but we won't enforce it.

In future, maybe have people vote with a commit in a repo. :)

**Comment by coke** [comment]
Can we close this issue now?
