### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by coke** [Raku/Raku-Steering-Council#23]
The initial release announcement discusses voting  and mentions that everyone voting can vote for each candidate with a value of 1..5 - but doesn't say what "winning" looks like.

I assume it's the candidates receiving the highest # of votes (adding all the value together), but we need some rules around how that translates to a win/loss (e.g. is it the top 5 candidates with the highest sum of votes?) Also what happens in the case of a tie?

Voting is supposed to start in less than a week, so we need to address this question.

**Comment by lizmat** [comment]
Would it make sense to follow the same logic as with the grant committee vote counting?

**Comment by vrurg** [comment]
@coke I guess [this section in the Code](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md#electing-the-council) has the answers. BTW, it's the top 7 who win, not 5.

**Comment by coke** [comment]
Thank you @vrurg - I completely misread the voting, it's a Y/N for up to 5 candidates (to lizmat's point, I was reading it like old TPF GC voting, which I've been using for years), then the top 7 vote getters win, modulo employer information (if I read other parts correctly) - Do we need to get candidates to list their employer on the nomination pages?

**Comment by vrurg** [comment]
> Do we need to get candidates to list their employer on the nomination pages?

Actually, it would make full sense.

**Comment by coke** [comment]
If it impacts the voting, I think we'd need to release it (or folks will have to trust me if someone's results get voided). But sure, please feel free to have folks send it to me privately

**Comment by lizmat** [comment]
I think it's more about a code of honour wrt employers.  Are we really going to check if two people are really employed by the same employer?  If that were true, and the stakes were high enough, for any big company it would be easy to move someone to a different daughter company for administrative purposes.

Should we ever really get to the point where the community would deem it incorrect for three people to be on the council, they could be asked to have one of them recuse themselves.  And if they don't, then there are other ways to make that happen.

**Comment by coke** [comment]
Based on discussion in IRC... I will report the results "as is", without collecting employer information. Winning candidates will have to attest that no one is in violation of the employer rule. I would prefer that we document it's easier to enforce, but doing it this way doesn't make it any more difficult to tally the votes.

**Comment by coke** [comment]
Added https://github.com/Raku/Raku-Steering-Council/blob/main/nominations/2020/voting-form.md
