### ISSUE TITLE
Note on the ballot that one votes for 0-5 names to fill 7 seats

### ISSUE THREAD

**Issue by tbrowder** [Raku/Raku-Steering-Council#24]

**Comment by AlexDaniel** [comment]
What do you mean 0-5 names?

> A formatted email template will be provided which voters can use to assign a value of 1 through 5 to each of the candidates of their choice. A voter sends the email to will@coleda.com for this initial election.

If I'm reading it correctly, you can assign a value of 1…5 to any number of names.
Also, the text sort of implies that you cannot write 0 or nothing, although logically a person should be allowed not to vote for somebody at all.

@coke can you please clarify?

**Comment by coke** [comment]
https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md#electing-the-council

Phase 2 under "Electing the Council" indicates you can vote for up to 5 candidates. So rather than ranked voting, it's "yes" only, and then we'll tally the yes votes. You can submit a vote that lists 0 candidates.

**Comment by AlexDaniel** [comment]
Ah, I see it now. It's across two different files. @tbrowder++, it should be made clear indeed.

**Comment by tbrowder** [comment]
The note about seven needs to be at the top.

Also a note that voting for more than five invalidates the vote (if that is true).

**Comment by AlexDaniel** [comment]
> Also a note that voting for more than five invalidates the vote (if that is true).

Not true, as clarified by @coke above! Sorry for the confusion.

**Comment by tbrowder** [comment]
On Tue, Sep 1, 2020 at 12:24 Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> Also a note that voting for more than five invalidates the vote (if that
> is true).
>
> Not true, as clarified by @coke <https://github.com/coke> above! Sorry
> for the confusion.
>
I don't see anything about voting for more than five people.

**Comment by coke** [comment]
Added a note about count > 5.

**Comment by AlexDaniel** [comment]
@coke actually, I don't understand. Can we go through it again, please?

There's this file: https://github.com/Raku/Raku-Steering-Council/blob/main/announcements/20200720.md.

It talks about the “initial election”, which is the upcoming one, as I understand. Then it says:

> A formatted email template will be provided which voters can use to assign a value of 1 through 5 to each of the candidates of their choice. A voter sends the email to will@coleda.com for this initial election.

So, according to that text, *for the initial election*, I would have to choose my candidates and assign a value 1-5 to each of them.

But then you say:

> Phase 2 under "Electing the Council" indicates you can vote for up to 5 candidates. So rather than ranked voting, it's "yes" only, and then we'll tally the yes votes. You can submit a vote that lists 0 candidates.

Why is it “yes” only? That document is for the active council, not for the initial election. Am I misunderstanding something?

This whole thing is very confusing.

**Comment by coke** [comment]
I took my notes from https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md - It looks like we have, for some reason, two different voting mechanisms described.

@lizmat ? Is this intentional? Were they both meant to be the same, or are they intended to be different, in which case I need to update the voting form?

**Comment by coke** [comment]
If the intent is 0-5 ranking, we're missing more language here - which is better, 0 or 5? How do we calculate the winner? (if 5 is better, we can do a sum. if we're ranking candidates in preference with lower number higher, that's a different algorithm.)

**Comment by vrurg** [comment]
I would say that the ranked voting mentioned in the announcement is a mistake and should be ignored and/or corrected. In either case the announcement is not the code and as such it can only describe but not define the rules. For this reason I think it must be ignored for now.

**Comment by vrurg** [comment]
If nobody minds the correction provided with #27 we can merge it to get rid of the discrepancy.

**Comment by coke** [comment]
With #27 merged, closing this ticket. Please re-open if anything still unclear.
