### ISSUE TITLE
Voting Rules (timing)

### ISSUE THREAD

**Issue by coke** [Raku/Raku-Steering-Council#33]
In future, don't use "midnight" as a cutoff time for voting. While there is a technical definition (it starts the day, not ends it), the common usage allows for ambiguity. Instead, use a non-ambiguous time, e.g. 11:59PM

**Comment by duncand** [comment]
100% support!  And further, midnight should never be used for any kind of deadline or start time period, any tiny offset either before or after should always be used.

**Comment by codesections** [comment]
This is a good point to keep in mind, but I don't believe it needs to stay open to serve that function.  Please feel free to re-open if you disagree.
