### ISSUE TITLE
Making announcements

### ISSUE THREAD

**Issue by lizmat** [Raku/Raku-Steering-Council#4]
The Raku community at the moment has no real way to announce things like the preliminary RSC, or the election.  This will probably become something on a rakufoundation.org website in the future, but we don't have that now.

**Comment by codesections** [comment]
We have adopted the practice of linking to documents in the `/announcements` folder as suggested above.  If, at some later point, we want to add a full blog, we can discuss that in a later issue, so I'm closing this for now.
