### ISSUE TITLE
What is FEZ?

### ISSUE THREAD

**Issue by finanalyst** [Raku/Raku-Steering-Council#46]
a) Is this the best way to address the Council, or would it be better to use another method, eg., email to perl6-users?
b) I noticed 'fez' in some zef output, and then I read the latest minutes of the Council to see what's happening.
But I could not quickly find a reference to fez as an ecosystem, or any indication that I should not use p6c as the ecosystem for publishing a module. I looked in the 'modules' page of the docs, and fez is not mentioned. 
I haven't used the new CPAN because I don't want to set up a PAUSE account, which I think is needed.

**Comment by lizmat** [comment]
If you want to speak privately to the RSC, there's the rsc@raku.org mail address.

To be able to publish modules on CPAN, you need a PAUSE account indeed.  At this point in time, I would not recommend going through the trouble for that.

The naming is still a bit in flux: but I think you can think of the "zef" ecosystem as a CPAN for Raku, and "fez" as PAUSE for the "zef" ecosystem.  Does that make sense?

**Comment by tony-o** [comment]
Fez is discussed in some detail here: https://docs.raku.org/language/modules#Preparing_the_module

If the docs leave questions unanswered I'd be happy to update

**Comment by finanalyst** [comment]
closed as resolved and moot
